### ISSUE TITLE
Which meta-data related keywords should be required?

### ISSUE THREAD

**Issue by jviotti** [JSON-UNIFY/vocab-dataset#21]
@RonItelman I think the current JSON Unify says that ALL meta keywords are required. Is that intentional? Should a subset be required instead?

**Comment by jviotti** [comment]
Once we collect a list, we can make them actually required in the meta-schema

**Comment by RonItelman** [comment]
@jviotti I think you are correct, that a subset makes the most amount of sense. I imagine the absolute minimal would be:

1. Source reference to data if no dataset is included
2. Description: primarily to imagine the developer experience, they need to know what the dataset is about.

I think the normal JSON-Schema object would cover specification. 

"Contract" was Cameron's perspective on a "Catalog of contracts" which would basically be like if you had to join 10 different datasets, you could have a list/object showing the 10 other objects and any information/'data contract' needed to join them. This is separate from Graph, which is where he would place actual mappings (and I have no idea how he was planning on doing it). Therefore "Contract" seems optional as well.

"Authors" seems optional, as does "Name".

Can't think of any others off the top of my head.

Does that work?

**Comment by jviotti** [comment]
@RonItelman 

> Description: primarily to imagine the developer experience, they need to know what the dataset is about.

Sounds like "Title" should be required and "Description" be optional instead. What do you think?

**Comment by RonItelman** [comment]
That makes sense. I'm assuming a title can give a short context to serve the purpose of enhancing the developer experience to know what the data set is about. For more details information can go into description. Sounds good!

**Comment by RonItelman** [comment]
Going back to the paradigm of "constraints design", or can/can't constructor-theoretic approaches:

A dataset:

*cannot* have no information about it, it must have at minimum a title

*Can* have no data, but *cannot* have no data without meta-data having a source url to a dataset.

Does that work?

**Comment by RonItelman** [comment]
And then to extended to concepts, and this is where I don't know if you want to adopt the full JSON unify approach, but the idea of guaranteeing to have schema information about the concepts within the data set.

**Comment by jviotti** [comment]
Makes sense! First of all, I'm making `title` required here: https://github.com/JSON-UNIFY/vocab-dataset/pull/23

**Comment by jviotti** [comment]
> Can have no data, but cannot have no data without meta-data having a source url to a dataset.

Fixed here: https://github.com/JSON-UNIFY/vocab-dataset/pull/24

**Comment by jviotti** [comment]
> And then to extended to concepts, and this is where I don't know if you want to adopt the full JSON unify approach, but the idea of guaranteeing to have schema information about the concepts within the data set.

I think that can be done too. Let me open a separate issue for it.
